name: Upload to Azure Storage

on:
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - uses: zeiss/az-storage-upload@c2bf34301cb9eddf0afc99c6a1b5d7d5e6d2ed52
        with:
          path: ./out
          container_name: $www
          account_url: ${{ secrets.AZURE_STORAGE_ACCOUNT_URL }}